server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: data-dictionary
  datasource:
    url: jdbc:mysql://120.55.194.122:3306/springboot?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Mime119321+-
  redis:
    host: localhost
    port: 6379
logging:
  level:
    com.bosssoft.hr.train.datadictionary.mapper: debug
